### ISSUE TITLE
not compatible with networkx 2.x module

### ISSUE THREAD

**Issue by vtslab** [pyannote/pyannote-algorithms#6]
#### Description
pyannote-algorithms requires networkx version 1.x Current is 2.x but due to API changes are they not compatible.

#### Steps/Code to Reproduce
pip list
to show the networkx version

To make it compatible with the networkx 2.x API I suggest the following changes to  pyannote-algorithms/pyannote/algorithms/clustering/hac/history.py:

- clusters = topological_sort(g, nbunch=clusters, reverse=True)
+ clusters = list(reversed(list(topological_sort(g.subgraph(clusters)))))

#### Versions

pyannote.algorithms==0.7.3
pyannote.core==1.3.1
pyannote.parser==0.7.1
pyannote.video==1.5.1

**Comment by hbredin** [comment]
Thanks for your feedback. I'd be happy to merge a pull request fixing the issue!
